export const llamaLockerAbi = [
	{
		type: "constructor",
		inputs: [
			{ name: "owner_", type: "address", internalType: "address" },
			{ name: "nft_", type: "address", internalType: "address" },
			{ name: "root_", type: "bytes32", internalType: "bytes32" },
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "EPOCH_DURATION",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "LOCK_DURATION_IN_EPOCH",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "acceptOwnership",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "addRewardTokens",
		inputs: [{ name: "tokens_", type: "address[]", internalType: "address[]" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "claim",
		inputs: [{ name: "recipient_", type: "address", internalType: "address" }],
		outputs: [
			{
				name: "results",
				type: "tuple[]",
				internalType: "struct locker.Claimable[]",
				components: [
					{ name: "token", type: "address", internalType: "address" },
					{ name: "amount", type: "uint256", internalType: "uint256" },
				],
			},
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "claimable",
		inputs: [
			{ name: "account_", type: "address", internalType: "address" },
			{ name: "token_", type: "address", internalType: "address" },
		],
		outputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "claimables",
		inputs: [{ name: "account_", type: "address", internalType: "address" }],
		outputs: [
			{
				name: "results",
				type: "tuple[]",
				internalType: "struct locker.Claimable[]",
				components: [
					{ name: "token", type: "address", internalType: "address" },
					{ name: "amount", type: "uint256", internalType: "uint256" },
				],
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "disableWhitelist",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "distributeRewardToken",
		inputs: [
			{ name: "token_", type: "address", internalType: "address" },
			{ name: "amount_", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "getClaimedRewards",
		inputs: [{ name: "account_", type: "address", internalType: "address" }],
		outputs: [
			{
				name: "results",
				type: "tuple[]",
				internalType: "struct locker.Claimable[]",
				components: [
					{ name: "token", type: "address", internalType: "address" },
					{ name: "amount", type: "uint256", internalType: "uint256" },
				],
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "getLocks",
		inputs: [],
		outputs: [
			{
				name: "results",
				type: "tuple[]",
				internalType: "struct locker.NFTLock[]",
				components: [
					{ name: "owner", type: "address", internalType: "address" },
					{ name: "lockedAt", type: "uint256", internalType: "uint256" },
					{ name: "tokenId", type: "uint256", internalType: "uint256" },
				],
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "getLocksByOwner",
		inputs: [{ name: "owner_", type: "address", internalType: "address" }],
		outputs: [
			{
				name: "results",
				type: "tuple[]",
				internalType: "struct locker.NFTLock[]",
				components: [
					{ name: "owner", type: "address", internalType: "address" },
					{ name: "lockedAt", type: "uint256", internalType: "uint256" },
					{ name: "tokenId", type: "uint256", internalType: "uint256" },
				],
			},
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "getRewardTokenCount",
		inputs: [],
		outputs: [{ name: "count", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "getRewardTokens",
		inputs: [],
		outputs: [
			{ name: "results", type: "address[]", internalType: "address[]" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "lock",
		inputs: [
			{ name: "tokenIds_", type: "uint256[]", internalType: "uint256[]" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "lock",
		inputs: [
			{ name: "proof_", type: "bytes32[]", internalType: "bytes32[]" },
			{ name: "tokenIds_", type: "uint256[]", internalType: "uint256[]" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "locks",
		inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
		outputs: [
			{ name: "owner", type: "address", internalType: "address" },
			{ name: "lockedAt", type: "uint256", internalType: "uint256" },
			{ name: "tokenId", type: "uint256", internalType: "uint256" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "nft",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "contract IERC721" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "onERC721Received",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "uint256", internalType: "uint256" },
			{ name: "", type: "bytes", internalType: "bytes" },
		],
		outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "owner",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "pendingOwner",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "renounceOwnership",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "rewardTokens",
		inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "root",
		inputs: [],
		outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "setRoot",
		inputs: [{ name: "root_", type: "bytes32", internalType: "bytes32" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "transferOwnership",
		inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "unlock",
		inputs: [
			{ name: "tokenIds_", type: "uint256[]", internalType: "uint256[]" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "whitelistDisabled",
		inputs: [],
		outputs: [{ name: "", type: "bool", internalType: "bool" }],
		stateMutability: "view",
	},
	{
		type: "event",
		name: "NewLocks",
		inputs: [
			{
				name: "owner",
				type: "address",
				indexed: false,
				internalType: "address",
			},
			{
				name: "tokenIds",
				type: "uint256[]",
				indexed: false,
				internalType: "uint256[]",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "NewRewardTokens",
		inputs: [
			{
				name: "token",
				type: "address[]",
				indexed: false,
				internalType: "address[]",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "NewRoot",
		inputs: [
			{
				name: "root",
				type: "bytes32",
				indexed: false,
				internalType: "bytes32",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "NewUnlocks",
		inputs: [
			{
				name: "owner",
				type: "address",
				indexed: false,
				internalType: "address",
			},
			{
				name: "tokenIds",
				type: "uint256[]",
				indexed: false,
				internalType: "uint256[]",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "OwnershipTransferStarted",
		inputs: [
			{
				name: "previousOwner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "newOwner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "OwnershipTransferred",
		inputs: [
			{
				name: "previousOwner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "newOwner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "RewardDistributed",
		inputs: [
			{
				name: "token",
				type: "address",
				indexed: false,
				internalType: "contract IERC20",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "WhitelistDisabled",
		inputs: [],
		anonymous: false,
	},
	{
		type: "error",
		name: "AddressEmptyCode",
		inputs: [{ name: "target", type: "address", internalType: "address" }],
	},
	{
		type: "error",
		name: "AddressInsufficientBalance",
		inputs: [{ name: "account", type: "address", internalType: "address" }],
	},
	{ type: "error", name: "FailedInnerCall", inputs: [] },
	{ type: "error", name: "InvalidAction", inputs: [] },
	{ type: "error", name: "InvalidLockOwner", inputs: [] },
	{ type: "error", name: "InvalidRecipient", inputs: [] },
	{ type: "error", name: "InvalidRewardAmount", inputs: [] },
	{ type: "error", name: "InvalidRewardToken", inputs: [] },
	{ type: "error", name: "InvalidTokenCount", inputs: [] },
	{ type: "error", name: "InvalidTotalShares", inputs: [] },
	{ type: "error", name: "InvalidUnlockWindow", inputs: [] },
	{ type: "error", name: "MathOverflowedMulDiv", inputs: [] },
	{
		type: "error",
		name: "OwnableInvalidOwner",
		inputs: [{ name: "owner", type: "address", internalType: "address" }],
	},
	{
		type: "error",
		name: "OwnableUnauthorizedAccount",
		inputs: [{ name: "account", type: "address", internalType: "address" }],
	},
	{ type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
	{
		type: "error",
		name: "SafeCastOverflowedUintToInt",
		inputs: [{ name: "value", type: "uint256", internalType: "uint256" }],
	},
	{
		type: "error",
		name: "SafeERC20FailedOperation",
		inputs: [{ name: "token", type: "address", internalType: "address" }],
	},
] as const;
